name: Deploy to Timeweb (Vite + FTP)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy via FTP to Timeweb
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.TIMEWEB_FTP_HOST }}
          username: ${{ secrets.TIMEWEB_FTP_USER }}
          password: ${{ secrets.TIMEWEB_FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.TIMEWEB_FTP_DIR }}
          protocol: ftps
          log-level: standard
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

